language: android
android:
  components:
     - platform-tools
     - tools
     - build-tools-22.0.1
     - android-22
     - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
    - "./gradlew publishApkRelease"

